const About =()=> {
    return(
        <>
            <h1>About</h1>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Alias consequatur esse non totam ullam? Alias consectetur consequatur cupiditate explicabo fuga incidunt, ipsam, maxime nemo omnis qui ratione tenetur! A blanditiis culpa facilis illo illum ipsam iste maiores necessitatibus nemo nesciunt nisi numquam omnis pariatur quod rerum temporibus, voluptate. Atque ducimus labore quidem tenetur voluptatibus? Aspernatur assumenda autem beatae cum dignissimos distinctio dolore doloremque dolores esse et, eum excepturi impedit in ipsam, laboriosam maxime minima nam nihil obcaecati quas quis, rem repellendus soluta tempore ullam? Accusantium aspernatur cumque dolorum iusto laborum nisi nobis quam, tempore? Aut non quam repellat repudiandae sed?</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda autem blanditiis, cum id ipsum minima molestias natus numquam provident repellendus sit soluta. Accusantium cumque cupiditate dolor est fugit, inventore iste itaque labore nam necessitatibus, nemo nobis nostrum numquam quaerat sint. Consectetur debitis deleniti dignissimos est fuga labore laboriosam magnam maiores natus necessitatibus nulla rem similique suscipit, tempora tenetur totam voluptatum! Ad corporis culpa cupiditate ex harum nam obcaecati quasi voluptas? Architecto aut autem consequatur, distinctio dolores eaque excepturi facilis fuga incidunt labore laudantium necessitatibus nobis nostrum odio omnis pariatur placeat, porro possimus quo ratione repellat similique tempora temporibus ut voluptas.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet, animi, commodi consectetur dolorem ducimus hic incidunt ipsum labore libero magni natus quas, quibusdam rerum saepe sapiente soluta tempore temporibus totam? Ab, accusamus ad aliquid aperiam, beatae cum, cupiditate delectus eligendi est et eum ex hic illo inventore libero magnam nesciunt officia perspiciatis quae quis repellat repellendus repudiandae rerum saepe temporibus? Beatae cupiditate debitis dolor dolorum eos et excepturi exercitationem expedita hic ipsa ipsam optio placeat quasi qui quis, recusandae reiciendis sequi soluta, vitae voluptates. Accusamus aliquam aperiam est incidunt numquam odio, provident tempore! Alias consectetur dignissimos eum incidunt labore magnam modi nam perspiciatis sapiente, sed. Aliquid hic id in, ipsam laborum maiores nemo ratione repellendus sint tenetur. Aliquam aliquid architecto aspernatur atque doloribus ea, eos ex explicabo fuga id illum iure iusto libero molestiae mollitia nisi non obcaecati omnis placeat porro, quasi quidem, rem saepe tempora veniam veritatis voluptatibus voluptatum!</p>
        </>
    )
}
export default About;